### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Wolfyxon** [Wolfyxon/lover#1]
# 2.3.0
- [x] Ignoring file if `---@lover:ignoreFile` is present at the top
- [x] Rename `[directories]` -> `[paths]` while keeping compatibility
- [x] Rename `source` to `main` while keeping compatibility
- [ ] `init` command
- [ ] Running with love downloaded from deps

# Other
- [ ] AUR
  - [x] PKGBUILDs 
    - [x] latest source code (`lover-git`)
    - [x] latest release source code (`lover`)
  - [ ] Test on clean install
    - [ ] `lover`
    - [ ] `lover-git` 
  - [ ] Submit to the AUR
    - [ ] `lover-git`
    - [ ] `lover` 

# No version goal / future
- [ ] Verifying downloads with the SHA256 provided by GitHub (they added it recently)
- [ ] Output code optimization
  - [ ] Copying optimized files into a build dir
    - [ ] Hashing files to prevent constant recopying  
  - [ ] Removing comments
  - [ ] Removing newline chars 
- [ ] Optional compiling with luajit
  - [x] Compiling source
  - [ ] Compiling generated `conf.lua`
  - [ ] Applying to build targets (with proper architecture)
- [ ] Unit testing
- [ ] Conditional compilation (maybe)
- [ ] Code obfuscation
- [ ] Better dependencies
   - [ ] Installing from a local file automatically
   - [ ] Choosing a specific version / commit
  - [ ] LovePotion nest support
    - [x] Downloading nest source
    - [ ] Running with nest 
  
- [ ] Design a logo
- [ ] Install script
- [ ]  Ignoring files and dirs in build, like .gitignore does
 - [ ] Modifying EXEs without `rcedit`
- [ ] Signing builds with `gpg` (if enabled)
- [ ] More advanced build targets
  - [ ] Android
  - [ ] Web
  - [ ] Nintendo 3DS
    - [ ] 3DS 3dsx (online using the LovePotion bundler API)
    - [ ] 3DS 3dsx (offline with DevkitPro)
      - [x] LovePotion deps
         - [x] 3ds
         - [x] assets  
      - [ ] Converting fonts to `bcfnt`
      - [ ] Converting images to `t3x` 
    - [ ] Installable CIA
  - [ ] #2
